# image will be published to ghcr.io/<user>/<name>
name: rh-meatwad
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    install:
      - gnome-clocks # for Panel World Clock GNOME extension
      - krb5-workstation # for kerberos support
      - libvirt-daemon-kvm # virt support
      - lm_sensors # for Freon GNOME extension
      - make # for making
      - openssh-askpass # ???
      - qemu-kvm # virt support
      - swtpm # virt support
      - virt-install # virt support
      - virt-manager # virt support
      - virt-viewer # virt support

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - org.localsend.localsend_app

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

